language: go
go:
  - "1.9"
go_import_path: github.com/fabianmatern/spike-travis-go
install: 
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u github.com/onsi/ginkgo/ginkgo
  - go get -u github.com/onsi/gomega/... 
  - export PATH=$PATH:$HOME/gopath/bin
script:
  - dep ensure -vendor-only
  - ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --compilers=2

