language: go
go:
  - "1.9"
install: 
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u github.com/onsi/ginkgo/ginkgo
  - go get -u github.com/onsi/gomega/... 
  - export PATH=$PATH:$HOME/gopath/bin
script:
  - cd src/github.com/dydyistc/spike-travis-go && dep ensure -vendor-only
  - ginkgo -r --randomizeAllSpecs --randomizeSuites --race --trace  && go vet

