language: go
go:
  - "1.9"
go_import_path: github.com/fabianmatern/spike-travis-go
script: 
  - git clone --depth 1 --branch v0.3.0 https://github.com/golang/dep.git $GOPATH/src/github.com/golang/dep && cd $GOPATH/src/github.com/golang/dep/cmd/dep && go install .
  - go get -u github.com/onsi/ginkgo/ginkgo
  - go get -u github.com/onsi/gomega/... 
  - dep ensure -vendor-only
  - $GOPATH/bin/ginkgo -tags unitTests src/github.com/fabianmatern/spike-travis-go/...
